### ISSUE TITLE
IDEA: site build then package

### ISSUE THREAD

**Issue by bryanjhv** [jekyll/jekyll-docs#10]
The gems works like a charm, doing what it says. But there are still some Jekyll users that run it on Windows, and re-building the site every time we do `jekyll docs` sometimes takes a long time to just build, and disk space of course.

So the idea is: build the site on `bundle exec rake build`, then change the code to just serve it with the default Jekyll `serve` command. Maybe it needs to get a lot of dependencies (`jekyll-feed` and others used by the docs site), but many will be thankful.

**Comment by parkr** [comment]
This is a great idea!!!

**Comment by bryanjhv** [comment]
It is, but there's a problem... I tried doing it, and with a bit of `Bundler.with_clean_env` and `bundle exec jekyll build -s staging -d site` can be solved, but the dependencies on Jekyll repository `Gemfile` are more than the ones we need.

Maybe a solution is to `gem 'github-pages'` and `gem 'pygments.rb'` to make it work. Then it's just a matter of `Rakefile`, `Gemfile` and `lib/jekylll-docs.rb` changes, and determining which Jekyll version is the `github-pages` gem using.
