### ISSUE TITLE
Unable to run command "jekyll docs" for version 3.1.6

### ISSUE THREAD

**Issue by tunjos** [jekyll/jekyll-docs#12]
I successfully installed jekyll-docs, but I get this error message
```bash
~ $ jekyll docs  
You must install the 'jekyll-docs' gem to use the 'jekyll docs' command.
```
I have installed
**jekyll-docs (3.1.6)**
**jekyll (3.1.6)**

Similar issues have been raised for earlier versions:   #5

**Comment by tunjos** [comment]
@parkr  Any thoughts? Thanks.

**Comment by parkr** [comment]
Yeah. "What the heck?" 😝

`jekyll-docs` locks down so it only runs with the exact same version of jekyll installed. Do you have any _other_ versions of jekyll-docs or jekyll installed? If you uninstall the other versions, does it work?

**Comment by tunjos** [comment]
I have uninstalled an older version **jekyll (3.0.3)**  
Now I have
**jekyll-docs (3.1.6)**
**jekyll (3.1.6)**  

Now I get the following.
```bash
~$ jekyll docs
Configuration file: ~/.rvm/gems/ruby-2.3.1/gems/jekyll-docs-3.1.6/site/_config.yml
            Source: ~/.rvm/gems/ruby-2.3.1/gems/jekyll-docs-3.1.6/site
       Destination: /tmp/d20160720-32394-hr56r4
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Dependency Error: Yikes! It looks like you don't have pygments or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- pygments' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
  Liquid Exception: pygments in ~/.rvm/gems/ruby-2.3.1/gems/jekyll-docs-3.1.6/site/_posts/2014-03-27-jekyll-1-5-1-released.markdown
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    pygments
``` 
I am sure Ill be bombarded with other dependencies.
Do I have to install all of them manually? or is there a quick fix?

**Comment by parkr** [comment]
Just 1 or 2 dependencies. This will be fixed in future versions by #11 :smile:

**Comment by tunjos** [comment]
```bash
~ $ gem install pygments.rb  
```
That's all I needed.
Works fine now. Thanks :+1:

**Comment by parkr** [comment]
Glad to hear! The 3.2.0 docs (and beyond) should avoid this issue altogether. 😄
