### ISSUE TITLE
Unable to run command "jekyll docs" for version 3.3.1

### ISSUE THREAD

**Issue by Gander7** [jekyll/jekyll-docs#15]
When I run the jekyll docs cmd I still an error.  Am I missing anything?
btw I love that you guys have this feature, since I do work offline quite a bit and enjoy having the docs, so thank you for supporting this option even though it seems it may have become a sore point.

- I am outside a project directory with no gemfile as per issue #14.
- I tried applying all fixes not pertaining to a gemfile I could see on issue #5, see below.
- Tried installing pygments.rb as per issue #12 with no change.

```
$uname -svrio
Linux 4.4.0-31-generic #50 Ubuntu x86_64 GNU/Linux (omitted version datetime)
$ ls -a
. .. testblog
$ gem list | grep jekyll
jekyll (3.3.1, 3.3.0)
jekyll-docs (3.3.0)
jekyll-feed (0.8.0)
jekyll-sass-converter (1.5.0)
jekyll-watch (1.5.0)
$ jekyll docs
You must install the 'jekyll-docs' gem to use the 'jekyll docs' command.
$ jekyll docs -v
docs
$ jekyll docs -h 
(shows usage documentation, omitted for brevity, btw there are two lines for -t, --trace)
$ jekyll docs --verbose --trace
jekyll 3.3.1 | Error: Whoops, we can't understand your command.
jekyll 3.3.1 | Error: invalid option: --verbose
jekyll 3.3.1 | Error: Run your command again with the --help switch to see available options.
$ jekyll docs --trace
You must install the 'jekyll-docs' gem to use the 'jekyll docs' command.
$ irb
irb> require 'jekyll-docs'
=> true
```

**Comment by DirtyF** [comment]
yeah 3.3.1 is not released but you still can launch docs with :

`jekyll _3.3.0_ docs`

@parkr What would it need to automate the release of a new `jekyll-doc` gem when a new version of Jekyll is released?

**Comment by parkr** [comment]
I just pushed up v3.3.1.

I don't know about automating, but we should have a checklist for every version that we can just copy/paste into an issue so we don't forget anything.
