### ISSUE TITLE
Create docs for 3.4.0

### ISSUE THREAD

**Issue by bih** [jekyll/jekyll-docs#17]
When the latest version of Jekyll being `3.4.0` (as of 31 Jan 2017), it seems the `jekyll-docs` gem on Rubygems.org doesn't work as the latest version of the `jekyll-docs` gem is 3.3.1.

Any news on when is this is launching or what I can do to get this up to date?

**Comment by gustavjf** [comment]
Having the same problem. Latest `jekyll` is 3.4.1, latest `jekyll-docs` is 3.3.1.

**Comment by parkr** [comment]
I shipped these docs Mar 22. Sorry about the delay! https://rubygems.org/gems/jekyll-docs/versions/3.4.0
