### ISSUE TITLE
Can't launch the "docs" site

### ISSUE THREAD

**Issue by jjarava** [jekyll/jekyll-docs#2]
I've installed the "docs" bundle following the instructions on the README at https://github.com/jekyll/jekyll-docs by adding `gem 'jekyll-docs'` to the Gemfile of my GitHub pages repo and running `Bundle`

Running `Bundle show' points to Jekyll-docs being installed:

```bash
jjarava$ bundle show jekyll-docs
/Library/Ruby/Gems/2.0.0/gems/jekyll-docs-1.0.0.pre.rc1
```

But trying to run either `bundle exec jekyll docs` or ` jekyll docs` gives an error:

```
jjarava$ bundle exec jekyll docs
Configuration file: none
            Source: /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/site
       Destination: /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/site/_site
      Generating...
jekyll 2.4.0 | Error:  No such file or directory - /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/site/
```

**Comment by andyw8** [comment]
I'm getting this too (1.0.0.pre.rc1).

**Comment by parkr** [comment]
@andyw8 It's only compatible with Jekyll 3, not with Jekyll 2 sadly.

**Comment by andyw8** [comment]
Ok, it would be helpful if you would update the repo description to make that clear.

(the information at the footer of http://jekyllrb.com/docs/usage/ led me here).

**Comment by parkr** [comment]
@andyw8 Done! Sorry about that.

You can get [docs on Dash.app](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Jekyll) if you use that. :)
